### PR TITLE
project SQL

### PR DESCRIPTION
**Pull request by ninjanocode**
the project that deals with sql

### CODE REVIEW

**Comment by melvyniandrag** [comment]
get your screenshot in of yourself running the code!

**Comment by ninjanocode** [comment]
I am not really sure how to do that using digial ocean. I am not sure if i
must connect my computer to digial ocean and send the photos there then use
the update the forked repo. Or if i must do something else that would allow
the photo go on the digital ocean server.

**Comment by melvyniandrag** [comment]
There are a few options and I'm available via email and discord whenever you are confused. I want the screenshot to make sure you have indeed run this code and not potentially just copied and pasted it.

**Comment by melvyniandrag** [comment]
extended the deadline for homework. Get the image in! You can upload an image right on github by clicking the **upload files** button. there are other options, but that is probably the easiest.

**Comment by ninjanocode** [comment]
I sent it here due to github saying it uploud are disabled as file uploaded
need push access to the repo

**Pull request merged**
