### PR TITLE
Exam Questions

### PR DESCRIPTION
**Pull request by gsanders1**
I was having some troubles uploading this to github. I just figured out how.

### CODE REVIEW

**Comment by melvyniandrag** [comment]
No message before the due date indicating a problem and github shows no work until late this afternoon.

sanders

**Comment by gsanders1** [comment]
Sorry, I had mixed up the due dates I thought it was due on the 18th.

**Comment by melvyniandrag** [comment]
Deadline is extended, don't miss another one! You've gotta get that grade up.

**Comment by melvyniandrag** [comment]
that let stuff is good, glad you learned something. That's not essential though, look at the code I wrote and you'll see I dont use that to count right/wrong, I just grep the $ANSWER_FILE to count how many rights/wrongs there are.

**Comment by melvyniandrag** [comment]
and you're missing a screenshot for homework 7.

**Comment by gsanders1** [comment]
Thanks. I just uploaded the photo for running the queries.

**Pull request merged**
