### PR TITLE
HW5

### PR DESCRIPTION
**Pull request by cteran13**
pw is first name.

### CODE REVIEW

**Comment by JulianAureliano** [comment]
No good. I don't know what the heck this is! Please explain? I could ssh in as Melvyn but it doesn't seem to be a linux server. Anyway, just use the digital ocean server and give me an ip you don't need a domain name yet.

**Comment by cteran13** [comment]
Ip address 68.183.16.160

**Comment by melvyniandrag** [comment]
IMG_20200224_110615


Double check that ssh key. Must be in /home/melvyn/.ssh/authorized_keys and must be correct and you must 'sudo service sshd restart'

**Comment by melvyniandrag** [comment]
my fault it works
I was using my work pc and not my laptop

**Pull request closed without merging**
