### PR TITLE
added myipaddress.txt in my directory

### PR DESCRIPTION
**Pull request by jvmanal**
After creating the text files for both "melvyn" and "virginia" as well as the .ssh folder (with authorized keys) I tried to cat the authorized keys in both melvyn and virginia, and just kept saying  "Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.208.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.208.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 409 [text/plain]" 
Not sure if I did it wrong.

### CODE REVIEW

**Comment by melvyniandrag** [comment]
That's wrong and you know it! We already discussed what an ssh key looks like, and I'm confident you understand it. So by any means possible, get my key there. There must be a problem with the way you ran the wget command. in the worst case scenario you can just type my key into the file, but that is a silly last resort way and not very elegant. You know wget, cp, git clone, etc so one of those tools ought to do it for you.

**Comment by jvmanal** [comment]
Hi Melvyn, just fixed the file, I realized that the "-O" was case sensitive [ended up using the lower case o instead so that was where my error was] so I ended up fixing the file for both melvyn and virigina.

**Comment by melvyniandrag** [comment]
Nice work I knew you'd figure it out.

**Comment by melvyniandrag** [comment]
I didn't teach you how to remove a file from version control, I see that you added the file in the wrong spot then fixed it. If there's time we'll talk about how to remove files from a  git repo, it's super easy. But there might not be time.

**Comment by jvmanal** [comment]
Yeah, I realized that when I was retracing my steps, I had files in the wrong spots so instead of redoing it from scratch, I just needed to research a little bit and see how I could make it work. Also if there isn't enough time during the semester, would it be okay if I could contact you via discord towards the end of the semester?

**Comment by melvyniandrag** [comment]
Of course

**Comment by melvyniandrag** [comment]
Feel free to destroy your server btw everything works as expected.

**Pull request closed without merging**
