### PR TITLE
Week04 Homework

### PR DESCRIPTION
**Pull request by raheempayne4**

### CODE REVIEW

**Comment by raheempayne4** [comment]
Week04 Homework submission. Hopefully, I did the pull request correctly.

**Comment by melvyniandrag** [comment]
I'll give you credit either way, but I think the if syntax with [[]] needs a space after the double bracket? I think you need to say  `if [[ 1 < 2  ]]`

**Comment by melvyniandrag** [comment]
In fact, go in and fix your if script, it doesn't do anything now. You didn't define new number and old number, and to dereference them you need to say $newNumber

**Comment by raheempayne4** [comment]
I fixed the issue and it actually works now, I'm going to resubmit the script.

**Comment by melvyniandrag** [comment]
Now it looks correct! I'll merge this thing tomorrow night or Wednesday afternoon.

**Pull request merged**
